spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/skill_bridge}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# Swagger Config
springdoc:
  api-docs:
    enabled: false
# Client Config
api:
  url: http://localhost:8080
# JWT Config
jwt:
  key: ${JWT_SECRET}